name: Custom ComboBox Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Artifact_Path: 'Sample Applications/CustomComboBox/bin'
      Project_Path: 'Sample Applications/CustomComboBox/CustomComboBox.csproj'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: dotnet build $env:Project_Path --configuration ${{ matrix.configuration }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('custom-combobox-{0}', matrix.configuration) }}
        path: ${{ format('{0}/{1}/**', env.Artifact_Path, matrix.configuration) }}
        if-no-files-found: error